config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'pages/home'
  post 'pages/scoreboard'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
require 'octokit'

class PagesController < ApplicationController
  def home
  end

  def scoreboard
    username = params[:username]
    password = params[:password]
    repo = params[:repo]

    # authentication
    client = Octokit::Client.new(login: username, password: password)

    # repository
    repo = repo

    # get last 100 pull requests
    pulls = client.pull_requests(repo, state: 'all', per_page: 100)

    # filter by those created in past week
    start_date = Date.today - 7
    pulls = pulls.select { |pull| Date.parse(pull.created_at.to_s) > start_date }

    # get comments and reviews for each pull request
    comments = Array.new
    reviews = Array.new
    pulls.each do |pull| 
      comments.concat(client.pull_request_comments(repo, pull.number, per_page: 100))
      reviews.concat(client.pull_request_reviews(repo, pull.number, per_page: 100))
    end

    # scoreboard with login names and points
    scoreboard = Hash.new

    # populate the scoreboard
    pulls.each do |pull|
      if scoreboard.key?(pull.user.login)
        scoreboard[pull.user.login] += 12
      else
        scoreboard[pull.user.login] = 12
      end
    end

    comments.each do |comment|
      if scoreboard.key?(comment.user.login)
        scoreboard[comment.user.login] += 1
      else
        scoreboard[comment.user.login] = 1
      end
    end

    reviews.each do |review|
      if scoreboard.key?(review.user.login)
        scoreboard[review.user.login] += 3
      else
        scoreboard[review.user.login] = 3
      end
    end

    # sort the scoreboard
    @scoreboard = scoreboard.sort_by { |k, v| v }.reverse.to_h
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cnc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Press+Start+2P&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h2>GitHub Repository</h2>
<%= form_tag pages_scoreboard_path do %>
  <%= label_tag :username %>
  <%= text_field_tag :username %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= label_tag :repo %>
  <%= text_field_tag :repo %>
  <%= submit_tag 'submit' %>
<% end %>

app/views/pages/scoreboard.html.erb
<h2>GitHub Scoreboard</h2>
<ol>
<% @scoreboard.each do |k, v| %>
<li><%= k %>: <%= v %></li>
<% end %>
</ol>
<%= link_to 'back', root_path %>